<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>tripleo.elijah</groupId>
		<artifactId>automatic-anno</artifactId>
		<version>automatic-anno.2025-11</version>
	</parent>

	<artifactId>annotation-mustache</artifactId>
	<name>annotations</name>
	<description>annotations</description>
	<packaging>jar</packaging>
	<version>automatic-anno.2025-11</version>

	<properties>
		<maven-compiler-plugin.version>3.13.0</maven-compiler-plugin.version>
	</properties>

	<dependencies>

		<dependency>
			<!--<groupId>com.github.google.compile-testing</groupId>-->
			<groupId>com.github.google</groupId>
			<artifactId>compile-testing</artifactId>
			<version>af1eb87ae91e9d0fc95a226cecc5fc94b1691d8c</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>com.github.spullara.mustache.java</groupId>
			<artifactId>compiler</artifactId>
			<version>0.9.14</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>org.jetbrains</groupId>
			<artifactId>annotations</artifactId>
			<version>24.0.1</version>
		</dependency>

	</dependencies>

	<build>
		<resources>
			<resource>
				<directory>src/main/resources/META-INF/services</directory>
				<includes>
					<include>javax.annotation.processing.Processor</include>
				</includes>
				<targetPath>META-INF/services</targetPath>
			</resource>
			<resource>
				<directory>src/main/resources</directory>
				<includes>
					<include>tripleo/elijah/automatic_anno/mustache/jsonwriter.mustache</include>
				</includes>
				<targetPath>
					${project.build.directory}/classes
				</targetPath>
			</resource>
		</resources>

		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>${maven-compiler-plugin.version}</version>
				<configuration>
					<compilerArgument>-proc:none</compilerArgument>
				</configuration>
				<!--
				<configuration>
					<annotationProcessors>
						tripleo.elijah.automatic_anno.mustache.ToJsonProcessor
					</annotationProcessors>
				</configuration>
				-->
			</plugin>
		</plugins>
	</build>
</project>
