package tripleo.elijah.automatic_anno.mustache;

import com.google.common.collect.ImmutableList;
import com.google.common.truth.Truth;
import com.google.testing.compile.Compilation;
import com.google.testing.compile.CompilationSubject;
import com.google.testing.compile.JavaFileObjects;
import org.jetbrains.annotations.NotNull;
import org.junit.Test;

import javax.tools.JavaFileObject;
import java.io.IOException;
import java.util.List;
import java.util.Optional;

import static javax.tools.StandardLocation.CLASS_OUTPUT;
import static javax.tools.StandardLocation.SOURCE_OUTPUT;

public class ToJsonProcessorTest {

	@Test
	public void process() throws IOException {
		JavaFileObject helloWorld = JavaFileObjects.forSourceLines("HelloWorld.java",  //
																															 "package  tripleo.elijah.automatic_anno.mustache;", //
																															 "", //
																															 "@JsonObject", //
																															 "final class HelloWorld {", //
																															 "  void sayHello() {", //
																															 "System.out.println(\"hello!\");", //
																															 "  }", //
																															 "}");
		Compilation compilation = com.google.testing.compile.Compiler.javac().withProcessors(new ToJsonProcessor()).compile(helloWorld);

		CompilationSubject.assertThat(compilation).succeeded/*WithoutWarnings*/();

		// assertThat(compilation)
		// 	.hadErrorContaining("No types named HelloWorld!")
		// 	.inFile(helloWorld)
		// 	.onLine(23)
		// 	.atColumn(5);

		final Optional<JavaFileObject> fooClassFile = compilation.generatedFile(CLASS_OUTPUT, "tripleo/elijah/automatic_anno/mustache/HelloWorld.class");
		Truth.assertThat(fooClassFile.isPresent()).isTrue();
		final Optional<JavaFileObject> fooSourceFile = compilation.generatedFile(SOURCE_OUTPUT, "tripleo/elijah/automatic_anno/mustache/HelloWorldJsonWriter.java");
		Truth.assertThat(fooSourceFile.isPresent()).isTrue(); // fixme

		final ImmutableList<JavaFileObject> gfs = compilation.generatedFiles();
		Truth.assertThat(gfs.stream().map(Object::toString))//
			.containsExactlyElementsIn(List.of( //
																					"InMemoryJavaFileObject{uri=mem:///CLASS_OUTPUT/tripleo/elijah/automatic_anno/mustache/HelloWorldJsonWriter.class, kind=CLASS}", //
																					"InMemoryJavaFileObject{uri=mem:///CLASS_OUTPUT/tripleo/elijah/automatic_anno/mustache/HelloWorld.class, kind=CLASS}", //
																					"InMemoryJavaFileObject{uri=mem:///SOURCE_OUTPUT/tripleo/elijah/automatic_anno/mustache/HelloWorldJsonWriter.java, kind=SOURCE}" //
																				));

		final CharSequence fooSourceString = fooSourceFile.get().getCharContent(true); // fixme true/false
		Truth.assertThat(p(fooSourceString)).isEqualTo("package tripleo.elijah.automatic_anno.mustache;\n"     //
																										 + "\n"     //
																										 + "import javax.annotation.processing.Generated;\n"     //
																										 + "\n"     //
																										 + "/**\n"     //
																										 + " * Json writer for {@link HelloWorld}.\n"     //
																										 + " */\n"     //
																										 + "@Generated(\n"     //
																										 + "    value = \"tripleo.elijah.automatic_anno.mustache.HelloWorld\",\n"     //
																										 //	"    date = \"2025-11-29T08:07:01.738244447-05:00\",\n" +  //
																										 + "    comments = \"generated by ToJsonProcessor\"\n"   //
																										 + ")\n"   //
																										 + "public final class HelloWorldJsonWriter {\n"   //
																										 + "\n"   //
																										 + "  private HelloWorldJsonWriter() {\n"   //
																										 + "  }\n"   //
																										 + "\n"  //
																										 + "  /**\n"  //
																										 + "   * Creates an json object to the given {@link HelloWorld}.\n"  //
																										 + "   *\n"  //
																										 + "   * return json representation\n"  //
																										 + "   */\n"  //
																										 + "  public static String toJson(HelloWorld object) {\n"  //
																										 + "    StringBuilder builder = new StringBuilder(\"{\");\n"  //
																										 + "    builder.append(\"\\\"class\\\": \\\"\").append(object.getClass()).append(\"\\\"\");\n"  //
																										 + "    return builder.append(\"}\").toString();\n"  //
																										 + "  }\n"  //
																										 + "\n"  //
																										 + "}"  //
																										 + "\n"  //
																									);  //

		final JavaFileObject javaFileObject = fooClassFile.get();
		// final InputStream    inputStream    = javaFileObject.openInputStream();
		// final byte[]         bytes          = inputStream.readAllBytes();
		// getClass().getClassLoader().
		// inputStream.close();
		// fixme instrumental??
	}

	private String p(final CharSequence aFooSourceString) {
		StringBuilder           res      = new StringBuilder();
		final @NotNull String[] splitted = aFooSourceString.toString().split("\n");
		for (String s : splitted) {
			if (s.startsWith("    date = \"")) continue;
			res.append(s);
			res.append('\n');
		}
		return res.toString();
	}

	@Test
	public void two() {
		// HelloWorld2JsonWriter hw
	}
}

@JsonObject
class HelloWorld2 {
	void sayHello() {
		System.out.println("hello!");
	}
}